name: SonarScan

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master

jobs:
  SonarCloudScan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better analysis

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.projectKey=${{secrets.PROJECT_KEY}}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
           
 